import { CardWrapper, StatRow, CardLoading, CardError } from './Card';
import { formatTokenCount, formatCost } from '@/utils/tokenStats';
import {
  TokenIcon,
  DollarIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  DiamondOutlineIcon,
  DiamondFilledIcon,
  ZapIcon,
} from '@/components/icons';
import { getAdapter } from '@/providers/registry';
import type { TokensCardData } from '@/schemas/api';
import type { CardProps } from './types';
import styles from '../SessionSummaryPanel.module.css';

// Provider-neutral tooltips. The estimated-cost and fast-mode tooltips are
// resolved per-provider via the ProviderAdapter (CF-436).
const TOOLTIPS = {
  input: 'Total tokens sent to the model',
  output: 'Total tokens generated by the model',
  cacheCreated: 'Tokens written to cache for future use',
  cacheRead: 'Tokens served from cache (reduced cost)',
};

interface TokensCardProps extends CardProps<TokensCardData> {
  /** Session provider id (e.g. "claude-code" | "codex"). Resolves
   *  provider-specific tooltip copy on the Estimated cost / Fast mode rows. */
  provider: string;
}

/**
 * Registry-friendly wrapper. The card registry's generic component type
 * doesn't model `provider`; SessionSummaryPanel injects it at runtime via
 * extraProps. This wrapper defaults provider to "claude-code" as a runtime
 * fallback. Direct callers still get the TS-enforced required prop on
 * `TokensCard` itself. Mirrors ConversationCardForRegistry. (CF-436)
 */
export function TokensCardForRegistry(
  props: Omit<TokensCardProps, 'provider'> & { provider?: string }
) {
  return <TokensCard {...props} provider={props.provider ?? 'claude-code'} />;
}

export function TokensCard({ data, loading, error, provider }: TokensCardProps) {
  if (error && !data) {
    return <CardError title="Tokens" error={error} icon={TokenIcon} />;
  }

  if (loading && !data) {
    return (
      <CardWrapper title="Tokens" icon={TokenIcon}>
        <CardLoading />
      </CardWrapper>
    );
  }

  if (!data) return null;

  const adapter = getAdapter(provider);
  const cost = parseFloat(data.estimated_usd);
  const isZeroCost = cost === 0;
  const hasFastMode = data.fast_turns != null;
  // CF-436: Hide the "Cache created" row when the value is 0. OpenAI doesn't
  // bill cache writes (always 0 for Codex), and Claude sessions without
  // prompt caching shouldn't show a confusing "0 tokens" row either.
  const showCacheCreated = data.cache_creation > 0;
  const costTooltip = isZeroCost
    ? 'Cost unavailable — session may use models not yet in the pricing table'
    : adapter.tokensCostTooltip;

  return (
    <CardWrapper title="Tokens" icon={TokenIcon}>
      <StatRow
        label="Estimated cost"
        value={formatCost(cost)}
        icon={DollarIcon}
        tooltip={costTooltip}
        valueClassName={isZeroCost ? styles.costWarning : styles.cost}
      />
      {hasFastMode && (
        <StatRow
          label="Fast mode"
          value={formatCost(parseFloat(data.fast_cost_usd!))}
          icon={ZapIcon}
          tooltip={adapter.tokensFastTooltip}
          valueClassName={styles.costFast}
        />
      )}
      <StatRow
        label="Input"
        value={formatTokenCount(data.input)}
        icon={ArrowRightIcon}
        tooltip={TOOLTIPS.input}
      />
      <StatRow
        label="Output"
        value={formatTokenCount(data.output)}
        icon={ArrowLeftIcon}
        tooltip={TOOLTIPS.output}
      />
      {showCacheCreated && (
        <StatRow
          label="Cache created"
          value={formatTokenCount(data.cache_creation)}
          icon={DiamondOutlineIcon}
          tooltip={TOOLTIPS.cacheCreated}
        />
      )}
      <StatRow
        label="Cache read"
        value={formatTokenCount(data.cache_read)}
        icon={DiamondFilledIcon}
        tooltip={TOOLTIPS.cacheRead}
      />
    </CardWrapper>
  );
}
